In [2]:
import pandas as pd
import numpy as np

In [11]:
df = pd.DataFrame(np.random.uniform(0, 1, size=(25, 9)))

df[1] = df[1].round(2)
df[2] = 'a'
df[3] = df[3] * 100
pd.options.display.float_format = '{:,}'.format
df[4] = df[4] * 100
display(df)

       0     1  2      3     4     5     6     7     8
0   0.14  0.75  a  34.87  47.0  0.05  0.23  0.40  0.44
1   0.93  0.40  a  66.30   5.0  0.25  0.62  0.30  0.47
2   0.68  0.29  a  68.12  55.0  0.40  0.25  0.67  0.94
3   0.52  0.92  a  24.51  61.0  0.92  0.71  0.42  0.68
4   0.67  0.79  a  65.88  79.0  0.50  0.63  0.78  0.96
5   0.18  0.15  a  43.45  73.0  0.88  0.97  0.24  0.44
6   0.80  0.65  a  26.46  99.0  0.68  0.06  0.36  0.04
7   0.78  0.49  a  64.77  43.0  0.90  0.06  0.59  0.83
8   0.51  0.55  a  78.14  87.0  0.30  0.57  0.89  0.13
9   0.56  0.36  a  91.75  95.0  0.91  0.60  0.01  0.56
10  0.35  0.46  a  95.24  19.0  0.73  0.71  0.05  0.54
11  0.45  0.79  a   6.01  22.0  0.91  0.86  0.73  0.47
12  0.69  0.44  a  25.60  73.0  0.71  0.48  0.57  0.93
13  0.94  0.88  a  18.71  91.0  0.91  0.43  0.43  0.20
14  0.61  0.78  a  52.83  51.0  0.81  0.64  0.36  0.12
15  0.42  0.70  a  44.59  55.0  0.34  0.31  0.29  0.85
16  0.33  0.94  a  53.89  46.0  0.04  0.44  0.55  0.46
17  0.36  0.90  a  65.68  21.0  0.00  0.27  0.07  0.46
18  0.83  0.33  a  26.02  14.0  0.71  0.87  0.76  1.00
19  0.35  0.73  a  31.85  74.0  0.62  0.04  0.57  0.06
20  0.91  0.96  a  47.71   7.0  0.01  0.61  0.14  0.63
21  0.82  0.10  a  32.37  76.0  0.88  0.70  0.50  0.35
22  0.19  0.88  a  17.11   2.0  0.70  0.24  0.26  0.17
23  0.19  0.32  a  70.56  18.0  0.96  0.37  0.50  0.86
24  0.90  0.51  a  16.44  90.0  0.25  0.34  0.03  0.09

In [12]:
df = pd.DataFrame(np.random.uniform(1000, 10000, size=(25, 9)))

display(df)

,0,1,2,3,4,5,6,7,8
0,5675.337408,8245.395412,6518.964019,7482.477639,8776.757945,8109.534466,9022.655454,3011.932765,6114.034313
1,8121.743598,6175.764094,9195.922682,6152.266518,6624.356445,2820.872349,9949.256321,3735.076287,3470.767390
2,9147.543719,9119.686298,6755.262180,5950.036868,8403.000409,1436.287644,4885.980543,1474.130134,6554.814768
3,5410.816985,8998.182647,3632.619272,3351.828458,3115.510283,3207.039416,9836.907308,6494.293018,9708.372839
4,8088.513362,4570.541051,3814.681737,1802.777635,5577.460351,1267.229020,6789.160206,9950.546267,2568.825388
5,2446.047881,8021.501055,1889.027219,7702.464144,4634.654610,1960.438161,5695.942605,7738.204341,9362.641961
6,4612.621978,1367.386319,1963.054469,7209.703705,7469.066260,3684.674961,4358.808334,9358.710954,4107.825500
7,7992.758859,8259.110129,1311.328035,9999.996406,4916.737956,5695.687019,6540.286158,2118.389254,6913.743432
8,9908.615827,5924.316174,4732.732168,1192.673000,3175.354066,8896.293570,3917.101678,1021.100493,3339.436942
9,8197.948037,8788.541695,7054.651151,7175.098950,3160.603674,2921.208744,2529.936693,4391.620923,6755.323731
10,7386.543381,6520.099806,4548.000792,7389.013048,6528.902478,5817.547506,2593.177684,5396.106192,4184.064726
11,5687.772992,4767.739881,3840.930137,5775.722086,4991.456908,1243.761436,4689.515313,2244.091669,2276.070557
12,4297.943929,7971.837285,8983.458591,8768.474469,6689.379551,3425.160252,9667.926495,7980.580589,8347.085409
13,9470.306431,2238.263348,1348.880259,4418.877207,2873.360888,9262.838891,6837.133300,5315.307463,4649.103698
14,8346.550880,8611.979244,1797.429991,9230.130086,8908.994474,1508.466862,1391.907723,3651.232469,1797.383119
15,4146.862649,2935.385948,7605.515089,2449.645765,1004.547785,8819.601438,9909.526519,8102.766038,6440.662969
16,3718.872862,5993.727603,3069.145220,8213.599649,8325.894635,8226.384990,2499.692466,2578.010079,4370.549022
17,5392.279629,2163.132999,8173.550413,7093.714025,6200.075432,5767.156974,5911.988283,8843.585611,1394.047736
18,6684.372478,3259.478006,9013.466355,6753.194468,8045.206607,5277.213247,1168.900411,9924.701281,8528.835782
19,9917.092256,5463.482869,7501.008707,7807.007684,6580.894518,3224.307861,8085.442353,8410.124954,5550.649356
20,8493.017471,9387.479638,5065.768415,4973.237621,1672.276212,8072.734594,6912.638023,1311.664728,4617.532013
21,1446.251983,6085.683087,1074.971571,1857.955066,5654.165157,9703.982102,7457.296279,9647.895698,3964.085662
22,3080.167477,9197.045340,3469.140950,8521.304798,1834.097673,3776.669294,6670.782193,8063.123057,9567.905495
23,9221.524683,9897.906868,6715.950613,9614.482815,5723.280867,2253.807243,2864.113907,5732.669100,3760.694983
24,1407.912060,2505.340262,6404.282789,9042.737037,8854.773044,3356.845558,2708.094688,9176.150018,4180.229222